server:
 port: 8080
  
eureka:
 client:
  fetch-registry: true
  register-with-eureka: true
  service-url:
   default-zona: http://localhost:8761/eureka
 instance:
  hostname: localhost

spring:
 cloud:
  gateway:
   discovery:
    locator:
     enabled: true
   routes:
   - id: Reportes
     uri: lb://Reportes
     predicates:
      - path=/reporte/**
   - id: Horarios
     uri: lb://Horarios
     predicates:
      - path=/horario/**
   - id: Empleados
     uri: lb://Empleados
     predicates:
      - path=/empleado/**
